- base/_colors.scss
> DAT-4441 | colors-update

- base/_colors.scss
https://wikia-inc.atlassian.net/browse/DAT-4600
@Wikia/x-wing
> DAT-4600 Add fandom default link color

- components/_global-footer.scss
https://wikia-inc.atlassian.net/browse/XW-1750
> XW-1750 | Add styling for focused links in Global Footer

- components/_global-footer.scss
https://wikia-inc.atlassian.net/browse/XW-1758
> XW-1758 | Add wds- prefix

- bower.json
For https://wikia-inc.atlassian.net/browse/XW-1574 we need SVGs as a separate files, not sprites.
> Remove assets from ignored bower files

- components/_global-footer.scss
https://wikia-inc.atlassian.net/browse/XW-1787
@Wikia/x-wing
> XW-1787 | Full site link

- components/_global-footer.scss
Applied designer's feedback.
https://wikia-inc.atlassian.net/browse/XW-1856
@Wikia/x-wing
> XW-1856 | divider length on desktop; full site link appearance

- components/_global-footer.scss
https://wikia-inc.atlassian.net/browse/XW-1859
@Wikia/x-wing
> XW-1856 | fix line breaking for CJK languages (Chinese, Japanese, and Korean)

- components/_global-footer.scss
Reverts Wikia/design-system#29
> Revert "XW-1856 | fix line breaking for CJK languages (Chinese, Japanese, and Korean)"

- components/_global-footer.scss
https://wikia-inc.atlassian.net/browse/XW-1874
@Wikia/x-wing
> XW-1874 | adjust footer line height/list items spacing

- components/_lists.scss
- components/index.scss
https://github.com/Wikia/design-system-reference-page/pull/64
Duplicate for https://github.com/Wikia/design-system/pull/33, but target branch is `master` here
> XW-1619 | add list component styles

- components/_dropdowns.scss
> XW-1903 | Use $color-black for dropdown shadow

- base/_sizings.scss
- components/_buttons.scss
- components/_global-navigation.scss
> XW-1618 | Fix global nav for 1024px screens + tweak logo + change buttons color

- components/_dropdowns.scss
- components/_global-navigation.scss
- components/_lists.scss
- mixins/_ellipsis.scss
- mixins/index.scss
https://wikia-inc.atlassian.net/browse/XW-1877
https://github.com/Wikia/design-system-reference-page/pull/69
> XW-1877 | Search suggestions in Global Navigation

- components/_global-navigation.scss
> XW-1703 | Position notifications count in .wds-dropdown-toggle

- components/_global-navigation.scss
fix needed in: https://github.com/Wikia/app/pull/11241
task: https://wikia-inc.atlassian.net/browse/XW-1962
subtask (bug report): https://wikia-inc.atlassian.net/browse/XW-1926
@Wikia/x-wing
> XW-1926 | adjust nav width to match Oasis article on small breakpoint

- gulpfile.js
- reference-page/index.html
This is the only way to work around https://github.com/styledown/styledown/issues/2.
> Use `Wikia Design System` as the page title

- components/_global-navigation.scss
* https://wikia-inc.atlassian.net/browse/XW-2005
* https://github.com/Wikia/mercury/pull/2776
@Wikia/x-wing
> XW-2005 | add $global-navigation-outer-height variable

- tests/index.html
> fix running tests

- package.json
`package.json` version is outdated.
> Bump package.json to 4.1.0

- package.json
I did not follow docs here and messed it up...
> fix version in package.json

- package.json
Bump due to wrong release procedure.
> Bump package.json to 9.0.0

- .eslintrc.js
- .npmignore
- .travis.yml
- config/ember-try.js
- lib/post-build-copy/package.json
- package-lock.json
- package.json
this PR enable TRAVIS with ember test
> It's not wise to fly blindfolded

- app/components/wds-global-navigation.js
- app/components/wds-global-navigation/link-branded.js
- app/components/wds-global-navigation/link-dropdown.js
- app/components/wds-global-navigation/link.js
- app/templates/components/wds-global-navigation.hbs
- app/templates/components/wds-global-navigation/account-navigation.hbs
- app/templates/components/wds-global-navigation/dropdown.hbs
- app/templates/components/wds-global-navigation/link-authentication.hbs
- style-guide/styles/wds-components/_global-navigation.scss
- style-guide/styles/wds-variables/_typography.scss
- tests/dummy/app/index.html
- tests/dummy/app/models/global-navigation.json
- tests/dummy/app/templates/identity/global-navigation.hbs
https://wikia-inc.atlassian.net/browse/XW-4977
@Wikia/x-wing
> XW-4977 | Redesign global nav

- app/components/wds-avatar-stack.js
- app/components/wds-avatar.js
- app/components/wds-avatar/avatar-badge.js
- app/templates/components/wds-avatar-stack.hbs
- app/templates/components/wds-avatar.hbs
- app/templates/components/wds-community-header.hbs
- app/templates/components/wds-community-header/local-navigation-dropdown-level-2.hbs
- app/templates/components/wds-community-header/local-navigation-dropdown.hbs
- app/templates/components/wds-community-header/local-navigation.hbs
- app/templates/components/wds-global-navigation.hbs
- app/templates/components/wds-global-navigation/account-navigation.hbs
- app/templates/components/wds-global-navigation/dropdown.hbs
- app/templates/components/wds-global-navigation/link-authentication.hbs
- app/templates/components/wds-global-navigation/link-branded.hbs
- app/templates/components/wds-global-navigation/link-dropdown.hbs
- app/templates/components/wds-global-navigation/link.hbs
- package-lock.json
- package.json
- tests/dummy/app/controllers/route-components/avatars.js
- tests/dummy/app/helpers/i18n.js
- tests/dummy/app/routes/application.js
- tests/dummy/app/services/i18n.js
- tests/dummy/app/templates/route-components/avatars.hbs
- tests/integration/components/wds-avatar-test.js
https://wikia-inc.atlassian.net/browse/XW-4998
@Wikia/x-wing
> XW-4998 | Using i18next for reference page

- style-guide/styles/wds-components/_global-navigation.scss
> adjust button padding in wikis dropdown

- package-lock.json
- tests/dummy/app/models/global-navigation.json
- tests/dummy/app/templates/identity/api.hbs
https://wikia-inc.atlassian.net/browse/XW-5022
> XW-5022 | Update DS api docs on reference page

- app/templates/components/wds-global-navigation/anon.hbs
- style-guide/styles/wds-components/_global-navigation.scss
> remove unnecessary styles

- tests/dummy/app/templates/identity/global-navigation.hbs
> XW-4947 | Using proper GN variant names in hbs markup

- package-lock.json
- package.json
- tests/integration/components/wds-textarea-test.js
> Textarea tests

- app/components/wds-banner-notifications.js
- app/services/wds-banner-notifications.js
- app/templates/components/wds-banner-notifications.hbs
- package-lock.json
- package.json
- tests/integration/components/wds-banner-notifications-test.js
Move it from https://github.com/Wikia/announcements-front-end/pull/13
> Add wds-banner-notifications service and component

- app/models/wds-on-site-notifications/wds-on-site-notifications.js
https://wikia-inc.atlassian.net/browse/XW-5115
@Wikia/x-wing
> XW-5115 | support announcements notifications

- app/components/wds-global-navigation/user-modal.js
> XW-5121 | Use non-ember event handler for touchMove

- app/components/wds-avatar.js
- app/components/wds-dropdown-toggle.js
- app/components/wds-global-navigation.js
- app/components/wds-global-navigation/search.js
- app/templates/components/wds-community-bar/local-navigation-dropdown.hbs
- app/templates/components/wds-global-navigation.hbs
- app/templates/components/wds-global-navigation/search-modal.hbs
- app/templates/components/wds-global-navigation/user-modal.hbs
> Fix tracking of Global Nav elements

- app/templates/components/wds-global-navigation.hbs
> Global Nav | Use mobile sitename in glocal nav

- app/components/wds-on-site-notifications/notification-card.js
- app/models/wds-on-site-notifications/wds-on-site-notification.js
- app/models/wds-on-site-notifications/wds-on-site-notifications.js
- app/services/wds-on-site-notifications.js
- app/templates/components/wds-on-site-notifications/notification-card.hbs
https://wikia-inc.atlassian.net/browse/IRIS-6405
https://github.com/Wikia/app/pull/15736
@Wikia/iris
> IRIS-6405 | Use sendBeacon to mark notification as read on page unload

- app/services/wds-liftigniter.js
https://wikia-inc.atlassian.net/browse/XW-5216
> XW-5216 | Request site_name

- app/templates/components/wds-community-bar.hbs
- app/templates/components/wds-community-bar/local-navigation-level-2.hbs
- app/templates/components/wds-community-header/local-navigation-dropdown-level-2.hbs
- app/templates/components/wds-community-header/local-navigation-dropdown.hbs
- app/templates/components/wds-community-header/local-navigation.hbs
- app/templates/components/wds-dropdown-toggle.hbs
- tests/dummy/app/models/community-header.json
- tests/dummy/app/templates/partials/community-header-wiki-content.hbs
> Fix local navigation

- docs/404.html
- docs/index.html
- tests/dummy/config/environment.js
- tests/dummy/public/404.html
- tests/index.html
https://github.com/rafrex/spa-github-pages
This will add
- support for normal paths
- fix loading iframes on firefox
> support SPA links in Githubpages

- app/templates/components/community-header/local-navigation-dropdown-level-2.hbs
- app/templates/components/community-header/local-navigation.hbs
- app/templates/components/community-header/nav-item.hbs
- app/templates/components/dropdown-content.hbs
- tests/integration/components/community-header/local-navigation-test.js
- tests/integration/components/community-header/nav-item-test.js
also added tests for things that I have broken
Yes, we desperately need better coverage...
> Fix community header

- app/components/global-navigation/content-recommendations.js
Fix display of sponsored item thumbnails by making sure they use the same params as the other content recommendation cards.
https://wikia-inc.atlassian.net/browse/IW-1581
> IW-1581 | Apply thumbnailing params to sponsored item

- app/components/global-navigation/content-recommendations.js
https://wikia-inc.atlassian.net/browse/ER-21271?utm_term=&utm_source=jira-slack&utm_medium=referral-external
@Wikia/iwing
> ER-21271 | check if array is defined

- package-lock.json
- package.json
Reverts Wikia/design-system#338
> Revert "20.0.0"

- app/components/tracking-pixel.js
- app/templates/components/global-navigation/sponsored-content-card.hbs
- app/templates/components/tracking-pixel.hbs
> IW-2016 | Tracking pixel for sponsored content

- package.json
Updated version for the svg bug fix release 21.5.1
> Update version to 21.5.1

- app/components/global-navigation/content-recommendation-card.js
- app/components/global-navigation/content-recommendations.js
- app/components/global-navigation/sponsored-content-card.js
- app/templates/components/global-navigation/content-recommendations.hbs
> IW-2154 | Differentiate tracking label for sponsored content

- app/components/on-site-notifications/notification-card.js
- app/models/wds-on-site-notifications/wds-on-site-notification.js
- app/models/wds-on-site-notifications/wds-on-site-notifications.js
- app/utils/notification-types.js
- tests/integration/components/on-site-notifications/notification-card-test.js
- tests/unit/utils/notification-types-test.js
Ticket: https://wikia-inc.atlassian.net/browse/IW-2180
/cc @Wikia/iwing
> IW-2180 add support for atMentions in on-site-notifications I

- package-lock.json
- package.json
This reverts commit f435f477e870f2ba2969bb110c30af70a5c2e86e.
> Revert "22.11.0"

- app/components/global-navigation.js
- app/components/global-navigation/search.js
- app/templates/components/global-navigation/search.hbs
https://wikia-inc.atlassian.net/browse/SER-4349
> SER-4349 A/B/C adding drop down on Global Nav with a search scope [mweb]

- tests/integration/components/global-navigation/search-test.js
It sometimes breaks Jenkins pipeline. I left a comment with explanation
> IW-4970 Disable unstable test

- package.json
It was broken due to Jenkins deployment tests
> IW-4970 Update package version

- style-guide/styles/wds-mixins/_button-theming.scss
> Don't apply hover-like styles on focus state for button

- README.md
- package.json
- scripts/release-test.sh
> fix-release-test: Add test release script with option to pass

- app/components/global-navigation/search.js
- app/templates/components/global-navigation/search.hbs
- package.json
https://wikia-inc.atlassian.net/browse/SITE-1152
* adjust search suggestions to use prefixsearch api
* remove leftovers after local/cross-wiki search dropdown as it was used only in mobile-wiki
@Wikia/site-experience
> SITE-1152 | adjust search suggestions to use prefixsearch api
